// 小学1-3年生の漢字データベース
const kanjiData = {
  grade1: [
    // 数字・基本
    { kanji: '一', reading: 'いち', category: '数字' },
    { kanji: '二', reading: 'に', category: '数字' },
    { kanji: '三', reading: 'さん', category: '数字' },
    { kanji: '四', reading: 'し・よん', category: '数字' },
    { kanji: '五', reading: 'ご', category: '数字' },
    { kanji: '六', reading: 'ろく', category: '数字' },
    { kanji: '七', reading: 'しち・なな', category: '数字' },
    { kanji: '八', reading: 'はち', category: '数字' },
    { kanji: '九', reading: 'きゅう・く', category: '数字' },
    { kanji: '十', reading: 'じゅう', category: '数字' },
    { kanji: '百', reading: 'ひゃく', category: '数字' },
    { kanji: '千', reading: 'せん', category: '数字' },

    // 人・体
    { kanji: '人', reading: 'ひと', category: '人' },
    { kanji: '口', reading: 'くち', category: '体' },
    { kanji: '手', reading: 'て', category: '体' },
    { kanji: '足', reading: 'あし', category: '体' },
    { kanji: '目', reading: 'め', category: '体' },
    { kanji: '耳', reading: 'みみ', category: '体' },
    { kanji: '女', reading: 'おんな', category: '人' },
    { kanji: '男', reading: 'おとこ', category: '人' },
    { kanji: '子', reading: 'こ', category: '人' },
    { kanji: '王', reading: 'おう', category: '人' },

    // 自然
    { kanji: '山', reading: 'やま', category: '自然' },
    { kanji: '川', reading: 'かわ', category: '自然' },
    { kanji: '田', reading: 'た', category: '自然' },
    { kanji: '林', reading: 'はやし', category: '自然' },
    { kanji: '森', reading: 'もり', category: '自然' },
    { kanji: '石', reading: 'いし', category: '自然' },
    { kanji: '空', reading: 'そら', category: '自然' },
    { kanji: '水', reading: 'みず', category: '自然' },
    { kanji: '火', reading: 'ひ', category: '自然' },
    { kanji: '木', reading: 'き', category: '自然' },
    { kanji: '草', reading: 'くさ', category: '自然' },
    { kanji: '花', reading: 'はな', category: '自然' },
    { kanji: '貝', reading: 'かい', category: '自然' },
    { kanji: '虫', reading: 'むし', category: '動物' },
    { kanji: '犬', reading: 'いぬ', category: '動物' },

    // 時間・天気
    { kanji: '日', reading: 'ひ', category: '時間' },
    { kanji: '月', reading: 'つき', category: '時間' },
    { kanji: '年', reading: 'ねん・とし', category: '時間' },
    { kanji: '先', reading: 'さき', category: '時間' },
    { kanji: '生', reading: 'せい', category: '学校' },
    { kanji: '早', reading: 'はや', category: '時間' },
    { kanji: '夕', reading: 'ゆう', category: '時間' },
    { kanji: '天', reading: 'てん', category: '自然' },
    { kanji: '気', reading: 'き', category: '日常' },
    { kanji: '雨', reading: 'あめ', category: '自然' },
    { kanji: '竹', reading: 'たけ', category: '自然' },

    // 学校・学習
    { kanji: '学', reading: 'がく', category: '学校' },
    { kanji: '校', reading: 'こう', category: '学校' },
    { kanji: '字', reading: 'じ', category: '学校' },
    { kanji: '本', reading: 'ほん', category: '学校' },
    { kanji: '文', reading: 'ぶん', category: '学校' },
    { kanji: '名', reading: 'な', category: '学校' },

    // 方向・位置
    { kanji: '上', reading: 'うえ', category: '方向' },
    { kanji: '下', reading: 'した', category: '方向' },
    { kanji: '中', reading: 'なか', category: '方向' },
    { kanji: '大', reading: 'おお', category: '大きさ' },
    { kanji: '小', reading: 'しょう・ちい', category: '大きさ' },
    { kanji: '左', reading: 'ひだり', category: '方向' },
    { kanji: '右', reading: 'みぎ', category: '方向' },
    { kanji: '出', reading: 'で', category: '動作' },
    { kanji: '入', reading: 'い・はい', category: '動作' },
    { kanji: '外', reading: 'そと', category: '方向' },
    { kanji: '立', reading: 'た', category: '動作' },

    // 色・見た目
    { kanji: '白', reading: 'しろ', category: '色' },
    { kanji: '赤', reading: 'あか', category: '色' },
    { kanji: '青', reading: 'あお', category: '色' },

    // 生活
    { kanji: '町', reading: 'まち', category: '日常' },
    { kanji: '村', reading: 'むら', category: '日常' },
    { kanji: '車', reading: 'くるま', category: '日常' },
    { kanji: '門', reading: 'もん', category: '日常' },
    { kanji: '円', reading: 'えん', category: '数字' },
    { kanji: '玉', reading: 'たま', category: '日常' },
    { kanji: '金', reading: 'きん', category: '日常' },
    { kanji: '力', reading: 'ちから', category: '日常' },
    { kanji: '正', reading: 'せい', category: '日常' },
    { kanji: '見', reading: 'み', category: '動作' },
    { kanji: '音', reading: 'おと', category: '日常' },
  ],

  grade2: [
    // 自然・天気
    { kanji: '雲', reading: 'くも', category: '自然' },
    { kanji: '園', reading: 'えん', category: '学校' },
    { kanji: '遠', reading: 'とお', category: '方向' },
    { kanji: '何', reading: 'なに', category: '日常' },
    { kanji: '科', reading: 'か', category: '学校' },
    { kanji: '夏', reading: 'なつ', category: '時間' },
    { kanji: '家', reading: 'いえ', category: '日常' },
    { kanji: '歌', reading: 'うた', category: '日常' },
    { kanji: '画', reading: 'が', category: '学校' },
    { kanji: '回', reading: 'かい', category: '日常' },
    { kanji: '会', reading: 'かい', category: '日常' },
    { kanji: '海', reading: 'うみ', category: '自然' },
    { kanji: '絵', reading: 'え', category: '学校' },
    { kanji: '外', reading: 'そと', category: '方向' },
    { kanji: '角', reading: 'かど', category: '形' },
    { kanji: '楽', reading: 'がく・たの', category: '日常' },
    { kanji: '活', reading: 'かつ', category: '日常' },
    { kanji: '間', reading: 'あいだ', category: '時間' },
    { kanji: '丸', reading: 'まる', category: '形' },
    { kanji: '岩', reading: 'いわ', category: '自然' },
    { kanji: '顔', reading: 'かお', category: '体' },
    { kanji: '汽', reading: 'き', category: '日常' },
    { kanji: '記', reading: 'き', category: '学校' },
    { kanji: '帰', reading: 'かえ', category: '動作' },
    { kanji: '弓', reading: 'ゆみ', category: '日常' },
    { kanji: '牛', reading: 'うし', category: '動物' },
    { kanji: '魚', reading: 'さかな', category: '動物' },
    { kanji: '京', reading: 'きょう', category: '日常' },
    { kanji: '強', reading: 'つよ', category: '日常' },
    { kanji: '教', reading: 'おし・きょう', category: '学校' },
    { kanji: '近', reading: 'ちか', category: '方向' },
    { kanji: '兄', reading: 'あに', category: '人' },
    { kanji: '形', reading: 'かたち', category: '形' },
    { kanji: '計', reading: 'けい', category: '数字' },
    { kanji: '元', reading: 'もと', category: '日常' },
    { kanji: '言', reading: 'い・こと', category: '動作' },
    { kanji: '原', reading: 'はら', category: '自然' },
    { kanji: '戸', reading: 'と', category: '日常' },
    { kanji: '古', reading: 'ふる', category: '日常' },
    { kanji: '午', reading: 'ご', category: '時間' },
    { kanji: '後', reading: 'あと・うし', category: '時間' },
    { kanji: '語', reading: 'ご', category: '学校' },
    { kanji: '工', reading: 'こう', category: '日常' },
    { kanji: '公', reading: 'こう', category: '日常' },
    { kanji: '広', reading: 'ひろ', category: '大きさ' },
    { kanji: '交', reading: 'こう', category: '日常' },
    { kanji: '光', reading: 'ひかり', category: '自然' },
    { kanji: '考', reading: 'かんが', category: '動作' },
    { kanji: '行', reading: 'い・ゆ', category: '動作' },
    { kanji: '高', reading: 'たか', category: '大きさ' },
    { kanji: '黄', reading: 'き', category: '色' },
    { kanji: '合', reading: 'あ', category: '日常' },
    { kanji: '谷', reading: 'たに', category: '自然' },
    { kanji: '国', reading: 'くに', category: '日常' },
    { kanji: '黒', reading: 'くろ', category: '色' },
    { kanji: '今', reading: 'いま', category: '時間' },
    { kanji: '才', reading: 'さい', category: '日常' },
    { kanji: '細', reading: 'ほそ', category: '大きさ' },
    { kanji: '作', reading: 'つく', category: '動作' },
    { kanji: '算', reading: 'さん', category: '学校' },
    { kanji: '止', reading: 'と', category: '動作' },
    { kanji: '市', reading: 'し', category: '日常' },
    { kanji: '矢', reading: 'や', category: '日常' },
    { kanji: '姉', reading: 'あね', category: '人' },
    { kanji: '思', reading: 'おも', category: '動作' },
    { kanji: '紙', reading: 'かみ', category: '学校' },
    { kanji: '寺', reading: 'てら', category: '日常' },
    { kanji: '自', reading: 'じ', category: '日常' },
    { kanji: '時', reading: 'とき・じ', category: '時間' },
    { kanji: '室', reading: 'しつ', category: '日常' },
    { kanji: '社', reading: 'しゃ', category: '日常' },
    { kanji: '弱', reading: 'よわ', category: '日常' },
    { kanji: '首', reading: 'くび', category: '体' },
    { kanji: '秋', reading: 'あき', category: '時間' },
    { kanji: '週', reading: 'しゅう', category: '時間' },
    { kanji: '春', reading: 'はる', category: '時間' },
    { kanji: '書', reading: 'か', category: '学校' },
    { kanji: '少', reading: 'すこ', category: '大きさ' },
    { kanji: '場', reading: 'ば', category: '日常' },
    { kanji: '色', reading: 'いろ', category: '色' },
    { kanji: '食', reading: 'た・しょく', category: '日常' },
    { kanji: '心', reading: 'こころ', category: '日常' },
    { kanji: '新', reading: 'あたら', category: '日常' },
    { kanji: '親', reading: 'おや', category: '人' },
    { kanji: '図', reading: 'ず', category: '学校' },
    { kanji: '数', reading: 'かず', category: '数字' },
    { kanji: '西', reading: 'にし', category: '方向' },
    { kanji: '声', reading: 'こえ', category: '日常' },
    { kanji: '星', reading: 'ほし', category: '自然' },
    { kanji: '晴', reading: 'は', category: '自然' },
    { kanji: '切', reading: 'き', category: '動作' },
    { kanji: '雪', reading: 'ゆき', category: '自然' },
    { kanji: '船', reading: 'ふね', category: '日常' },
    { kanji: '線', reading: 'せん', category: '形' },
    { kanji: '前', reading: 'まえ', category: '方向' },
    { kanji: '組', reading: 'くみ', category: '学校' },
    { kanji: '走', reading: 'はし', category: '動作' },
    { kanji: '多', reading: 'おお', category: '大きさ' },
    { kanji: '太', reading: 'ふと', category: '大きさ' },
    { kanji: '体', reading: 'からだ', category: '体' },
    { kanji: '台', reading: 'だい', category: '日常' },
    { kanji: '地', reading: 'ち', category: '自然' },
    { kanji: '池', reading: 'いけ', category: '自然' },
    { kanji: '知', reading: 'し', category: '動作' },
    { kanji: '茶', reading: 'ちゃ', category: '日常' },
    { kanji: '昼', reading: 'ひる', category: '時間' },
    { kanji: '長', reading: 'なが', category: '大きさ' },
    { kanji: '鳥', reading: 'とり', category: '動物' },
    { kanji: '朝', reading: 'あさ', category: '時間' },
    { kanji: '直', reading: 'なお', category: '日常' },
    { kanji: '通', reading: 'とお', category: '動作' },
    { kanji: '弟', reading: 'おとうと', category: '人' },
    { kanji: '店', reading: 'みせ', category: '日常' },
    { kanji: '点', reading: 'てん', category: '学校' },
    { kanji: '電', reading: 'でん', category: '日常' },
    { kanji: '刀', reading: 'かたな', category: '日常' },
    { kanji: '冬', reading: 'ふゆ', category: '時間' },
    { kanji: '当', reading: 'あ', category: '日常' },
    { kanji: '東', reading: 'ひがし', category: '方向' },
    { kanji: '答', reading: 'こた', category: '学校' },
    { kanji: '頭', reading: 'あたま', category: '体' },
    { kanji: '同', reading: 'おな', category: '日常' },
    { kanji: '道', reading: 'みち', category: '日常' },
    { kanji: '読', reading: 'よ', category: '学校' },
    { kanji: '内', reading: 'うち', category: '方向' },
    { kanji: '南', reading: 'みなみ', category: '方向' },
    { kanji: '肉', reading: 'にく', category: '日常' },
    { kanji: '馬', reading: 'うま', category: '動物' },
    { kanji: '売', reading: 'う', category: '日常' },
    { kanji: '買', reading: 'か', category: '動作' },
    { kanji: '麦', reading: 'むぎ', category: '自然' },
    { kanji: '半', reading: 'はん', category: '数字' },
    { kanji: '番', reading: 'ばん', category: '数字' },
    { kanji: '父', reading: 'ちち', category: '人' },
    { kanji: '風', reading: 'かぜ', category: '自然' },
    { kanji: '分', reading: 'わ・ぶん', category: '時間' },
    { kanji: '聞', reading: 'き', category: '動作' },
    { kanji: '米', reading: 'こめ', category: '日常' },
    { kanji: '歩', reading: 'ある・ほ', category: '動作' },
    { kanji: '母', reading: 'はは', category: '人' },
    { kanji: '方', reading: 'ほう', category: '方向' },
    { kanji: '北', reading: 'きた', category: '方向' },
    { kanji: '毎', reading: 'まい', category: '時間' },
    { kanji: '妹', reading: 'いもうと', category: '人' },
    { kanji: '万', reading: 'まん', category: '数字' },
    { kanji: '明', reading: 'あか', category: '日常' },
    { kanji: '鳴', reading: 'な', category: '動作' },
    { kanji: '毛', reading: 'け', category: '体' },
    { kanji: '門', reading: 'もん', category: '日常' },
    { kanji: '夜', reading: 'よる', category: '時間' },
    { kanji: '野', reading: 'の', category: '自然' },
    { kanji: '友', reading: 'とも', category: '人' },
    { kanji: '用', reading: 'よう', category: '日常' },
    { kanji: '曜', reading: 'よう', category: '時間' },
    { kanji: '来', reading: 'く・らい', category: '動作' },
    { kanji: '里', reading: 'さと', category: '日常' },
    { kanji: '理', reading: 'り', category: '学校' },
    { kanji: '話', reading: 'はな・わ', category: '動作' },
  ],

  grade3: [
    // 生活・社会
    { kanji: '悪', reading: 'わる', category: '日常' },
    { kanji: '安', reading: 'やす', category: '日常' },
    { kanji: '暗', reading: 'くら', category: '日常' },
    { kanji: '医', reading: 'い', category: '日常' },
    { kanji: '委', reading: 'い', category: '学校' },
    { kanji: '意', reading: 'い', category: '日常' },
    { kanji: '育', reading: 'いく', category: '学校' },
    { kanji: '員', reading: 'いん', category: '日常' },
    { kanji: '院', reading: 'いん', category: '日常' },
    { kanji: '飲', reading: 'の', category: '日常' },
    { kanji: '運', reading: 'うん', category: '日常' },
    { kanji: '泳', reading: 'およ', category: '動作' },
    { kanji: '駅', reading: 'えき', category: '日常' },
    { kanji: '央', reading: 'おう', category: '方向' },
    { kanji: '横', reading: 'よこ', category: '方向' },
    { kanji: '屋', reading: 'や', category: '日常' },
    { kanji: '温', reading: 'おん', category: '自然' },
    { kanji: '化', reading: 'か', category: '学校' },
    { kanji: '荷', reading: 'に', category: '日常' },
    { kanji: '界', reading: 'かい', category: '日常' },
    { kanji: '開', reading: 'ひら・あ', category: '動作' },
    { kanji: '階', reading: 'かい', category: '日常' },
    { kanji: '寒', reading: 'さむ', category: '自然' },
    { kanji: '感', reading: 'かん', category: '日常' },
    { kanji: '漢', reading: 'かん', category: '学校' },
    { kanji: '館', reading: 'かん', category: '日常' },
    { kanji: '岸', reading: 'きし', category: '自然' },
    { kanji: '起', reading: 'お', category: '動作' },
    { kanji: '期', reading: 'き', category: '時間' },
    { kanji: '客', reading: 'きゃく', category: '日常' },
    { kanji: '究', reading: 'きゅう', category: '学校' },
    { kanji: '急', reading: 'いそ', category: '動作' },
    { kanji: '級', reading: 'きゅう', category: '学校' },
    { kanji: '宮', reading: 'みや', category: '日常' },
    { kanji: '球', reading: 'きゅう', category: '日常' },
    { kanji: '去', reading: 'さ', category: '動作' },
    { kanji: '橋', reading: 'はし', category: '日常' },
    { kanji: '業', reading: 'ぎょう', category: '日常' },
    { kanji: '曲', reading: 'きょく', category: '日常' },
    { kanji: '局', reading: 'きょく', category: '日常' },
    { kanji: '銀', reading: 'ぎん', category: '日常' },
    { kanji: '区', reading: 'く', category: '日常' },
    { kanji: '苦', reading: 'くる', category: '日常' },
    { kanji: '具', reading: 'ぐ', category: '日常' },
    { kanji: '君', reading: 'きみ', category: '人' },
    { kanji: '係', reading: 'かかり', category: '学校' },
    { kanji: '軽', reading: 'かる', category: '日常' },
    { kanji: '血', reading: 'ち', category: '体' },
    { kanji: '決', reading: 'き', category: '動作' },
    { kanji: '研', reading: 'けん', category: '学校' },
    { kanji: '県', reading: 'けん', category: '日常' },
    { kanji: '庫', reading: 'こ', category: '日常' },
    { kanji: '湖', reading: 'みずうみ', category: '自然' },
    { kanji: '向', reading: 'む', category: '方向' },
    { kanji: '幸', reading: 'しあわ', category: '日常' },
    { kanji: '港', reading: 'みなと', category: '日常' },
    { kanji: '号', reading: 'ごう', category: '日常' },
    { kanji: '根', reading: 'ね', category: '自然' },
    { kanji: '祭', reading: 'まつ', category: '日常' },
    { kanji: '皿', reading: 'さら', category: '日常' },
    { kanji: '仕', reading: 'し', category: '日常' },
    { kanji: '死', reading: 'し', category: '日常' },
    { kanji: '使', reading: 'つか', category: '動作' },
    { kanji: '始', reading: 'はじ', category: '動作' },
    { kanji: '指', reading: 'ゆび', category: '体' },
    { kanji: '歯', reading: 'は', category: '体' },
    { kanji: '詩', reading: 'し', category: '学校' },
    { kanji: '次', reading: 'つぎ', category: '時間' },
    { kanji: '事', reading: 'こと', category: '日常' },
    { kanji: '持', reading: 'も', category: '動作' },
    { kanji: '式', reading: 'しき', category: '日常' },
    { kanji: '実', reading: 'み', category: '日常' },
    { kanji: '写', reading: 'うつ', category: '動作' },
    { kanji: '者', reading: 'もの', category: '人' },
    { kanji: '主', reading: 'しゅ', category: '日常' },
    { kanji: '守', reading: 'まも', category: '動作' },
    { kanji: '取', reading: 'と', category: '動作' },
    { kanji: '酒', reading: 'さけ', category: '日常' },
    { kanji: '受', reading: 'う', category: '動作' },
    { kanji: '州', reading: 'しゅう', category: '日常' },
    { kanji: '拾', reading: 'ひろ', category: '動作' },
    { kanji: '終', reading: 'お', category: '動作' },
    { kanji: '習', reading: 'なら', category: '学校' },
    { kanji: '集', reading: 'あつ', category: '動作' },
    { kanji: '住', reading: 'す', category: '日常' },
    { kanji: '重', reading: 'おも', category: '大きさ' },
    { kanji: '宿', reading: 'やど', category: '日常' },
    { kanji: '所', reading: 'ところ', category: '日常' },
    { kanji: '暑', reading: 'あつ', category: '自然' },
    { kanji: '助', reading: 'たす', category: '動作' },
    { kanji: '昭', reading: 'しょう', category: '時間' },
    { kanji: '消', reading: 'き', category: '動作' },
    { kanji: '商', reading: 'しょう', category: '日常' },
    { kanji: '章', reading: 'しょう', category: '学校' },
    { kanji: '勝', reading: 'か', category: '日常' },
    { kanji: '乗', reading: 'の', category: '動作' },
    { kanji: '植', reading: 'う', category: '自然' },
    { kanji: '申', reading: 'もう', category: '動作' },
    { kanji: '身', reading: 'み', category: '体' },
    { kanji: '神', reading: 'かみ', category: '日常' },
    { kanji: '真', reading: 'しん', category: '日常' },
    { kanji: '深', reading: 'ふか', category: '大きさ' },
    { kanji: '進', reading: 'すす', category: '動作' },
    { kanji: '世', reading: 'せ', category: '日常' },
    { kanji: '整', reading: 'ととの', category: '動作' },
    { kanji: '昔', reading: 'むかし', category: '時間' },
    { kanji: '全', reading: 'ぜん', category: '日常' },
    { kanji: '相', reading: 'あい', category: '日常' },
    { kanji: '送', reading: 'おく', category: '動作' },
    { kanji: '想', reading: 'そう', category: '日常' },
    { kanji: '息', reading: 'いき', category: '体' },
    { kanji: '速', reading: 'はや', category: '日常' },
    { kanji: '族', reading: 'ぞく', category: '人' },
    { kanji: '他', reading: 'た', category: '日常' },
    { kanji: '打', reading: 'う', category: '動作' },
    { kanji: '対', reading: 'たい', category: '日常' },
    { kanji: '待', reading: 'ま', category: '動作' },
    { kanji: '代', reading: 'だい', category: '日常' },
    { kanji: '第', reading: 'だい', category: '数字' },
    { kanji: '題', reading: 'だい', category: '学校' },
    { kanji: '炭', reading: 'すみ', category: '日常' },
    { kanji: '短', reading: 'みじか', category: '大きさ' },
    { kanji: '談', reading: 'だん', category: '動作' },
    { kanji: '着', reading: 'き・つ', category: '動作' },
    { kanji: '注', reading: 'ちゅう', category: '動作' },
    { kanji: '柱', reading: 'はしら', category: '日常' },
    { kanji: '丁', reading: 'ちょう', category: '日常' },
    { kanji: '帳', reading: 'ちょう', category: '学校' },
    { kanji: '調', reading: 'しら', category: '動作' },
    { kanji: '追', reading: 'お', category: '動作' },
    { kanji: '定', reading: 'てい', category: '日常' },
    { kanji: '庭', reading: 'にわ', category: '日常' },
    { kanji: '笛', reading: 'ふえ', category: '日常' },
    { kanji: '鉄', reading: 'てつ', category: '日常' },
    { kanji: '転', reading: 'ころ', category: '動作' },
    { kanji: '都', reading: 'と', category: '日常' },
    { kanji: '度', reading: 'ど', category: '数字' },
    { kanji: '投', reading: 'な', category: '動作' },
    { kanji: '豆', reading: 'まめ', category: '日常' },
    { kanji: '島', reading: 'しま', category: '自然' },
    { kanji: '湯', reading: 'ゆ', category: '日常' },
    { kanji: '登', reading: 'のぼ', category: '動作' },
    { kanji: '等', reading: 'とう', category: '日常' },
    { kanji: '動', reading: 'うご', category: '動作' },
    { kanji: '童', reading: 'どう', category: '人' },
    { kanji: '農', reading: 'のう', category: '日常' },
    { kanji: '波', reading: 'なみ', category: '自然' },
    { kanji: '配', reading: 'くば', category: '動作' },
    { kanji: '倍', reading: 'ばい', category: '数字' },
    { kanji: '箱', reading: 'はこ', category: '日常' },
    { kanji: '畑', reading: 'はたけ', category: '自然' },
    { kanji: '発', reading: 'はつ', category: '動作' },
    { kanji: '反', reading: 'はん', category: '日常' },
    { kanji: '坂', reading: 'さか', category: '日常' },
    { kanji: '板', reading: 'いた', category: '日常' },
    { kanji: '皮', reading: 'かわ', category: '体' },
    { kanji: '悲', reading: 'かな', category: '日常' },
    { kanji: '美', reading: 'うつく', category: '日常' },
    { kanji: '鼻', reading: 'はな', category: '体' },
    { kanji: '筆', reading: 'ふで', category: '学校' },
    { kanji: '氷', reading: 'こおり', category: '自然' },
    { kanji: '表', reading: 'おもて', category: '学校' },
    { kanji: '秒', reading: 'びょう', category: '時間' },
    { kanji: '病', reading: 'びょう', category: '日常' },
    { kanji: '品', reading: 'しな', category: '日常' },
    { kanji: '負', reading: 'ま', category: '日常' },
    { kanji: '部', reading: 'ぶ', category: '学校' },
    { kanji: '服', reading: 'ふく', category: '日常' },
    { kanji: '福', reading: 'ふく', category: '日常' },
    { kanji: '物', reading: 'もの', category: '日常' },
    { kanji: '平', reading: 'たい', category: '日常' },
    { kanji: '返', reading: 'かえ', category: '動作' },
    { kanji: '勉', reading: 'べん', category: '学校' },
    { kanji: '放', reading: 'はな', category: '動作' },
    { kanji: '味', reading: 'あじ', category: '日常' },
    { kanji: '命', reading: 'いのち', category: '日常' },
    { kanji: '面', reading: 'めん', category: '日常' },
    { kanji: '問', reading: 'と', category: '学校' },
    { kanji: '役', reading: 'やく', category: '日常' },
    { kanji: '薬', reading: 'くすり', category: '日常' },
    { kanji: '由', reading: 'ゆう', category: '日常' },
    { kanji: '油', reading: 'あぶら', category: '日常' },
    { kanji: '有', reading: 'ゆう', category: '日常' },
    { kanji: '遊', reading: 'あそ', category: '動作' },
    { kanji: '予', reading: 'よ', category: '日常' },
    { kanji: '羊', reading: 'ひつじ', category: '動物' },
    { kanji: '洋', reading: 'よう', category: '日常' },
    { kanji: '葉', reading: 'は', category: '自然' },
    { kanji: '陽', reading: 'よう', category: '自然' },
    { kanji: '様', reading: 'さま', category: '日常' },
    { kanji: '落', reading: 'お', category: '動作' },
    { kanji: '流', reading: 'なが', category: '動作' },
    { kanji: '旅', reading: 'たび', category: '日常' },
    { kanji: '両', reading: 'りょう', category: '数字' },
    { kanji: '緑', reading: 'みどり', category: '色' },
    { kanji: '礼', reading: 'れい', category: '日常' },
    { kanji: '列', reading: 'れつ', category: '日常' },
    { kanji: '練', reading: 'ねり', category: '動作' },
    { kanji: '路', reading: 'ろ', category: '日常' },
    { kanji: '和', reading: 'わ', category: '日常' },
  ]
};

// 全漢字を1つの配列にまとめる
const allKanji = [...kanjiData.grade1, ...kanjiData.grade2, ...kanjiData.grade3];

// カテゴリ別の単語リスト
const vocabularyByCategory = {
  '動物': [
    { word: '犬', reading: 'いぬ' },
    { word: '虫', reading: 'むし' },
    { word: '牛', reading: 'うし' },
    { word: '魚', reading: 'さかな' },
    { word: '鳥', reading: 'とり' },
    { word: '馬', reading: 'うま' },
    { word: '羊', reading: 'ひつじ' },
  ],
  '学校': [
    { word: '学校', reading: 'がっこう' },
    { word: '教室', reading: 'きょうしつ' },
    { word: '先生', reading: 'せんせい' },
    { word: '図書館', reading: 'としょかん' },
    { word: '勉強', reading: 'べんきょう' },
    { word: '算数', reading: 'さんすう' },
    { word: '国語', reading: 'こくご' },
  ],
  '自然': [
    { word: '山', reading: 'やま' },
    { word: '川', reading: 'かわ' },
    { word: '海', reading: 'うみ' },
    { word: '空', reading: 'そら' },
    { word: '森', reading: 'もり' },
    { word: '花', reading: 'はな' },
    { word: '星', reading: 'ほし' },
  ],
  '日常': [
    { word: '家', reading: 'いえ' },
    { word: '車', reading: 'くるま' },
    { word: '時間', reading: 'じかん' },
    { word: '友達', reading: 'ともだち' },
    { word: '食事', reading: 'しょくじ' },
    { word: '買物', reading: 'かいもの' },
  ]
};
